In [1]:
import pandas as pd
import numpy as np

In [90]:
pd.__version__

'1.0.1'

In [43]:
with open('meteorite-landings.csv') as f:
   print(f)

<_io.TextIOWrapper name='meteorite-landings.csv' mode='r' encoding='cp1251'>

In [45]:
met=pd.read_csv('meteorite-landings.csv', encoding='cp1251')

In [46]:
met.head(2)

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,1880.0,50.77500,6.08333,"(50.775000, 6.083330)"
1,Aarhus,2,Valid,H6,720.0,Fell,1951.0,56.18333,10.23333,"(56.183330, 10.233330)"

In [61]:
# met.shape
# met.columns

# met.describe()
# met.info()

In [69]:
# отсортированная частота появления
    #met['mass'].value_counts(dropna=True)

In [70]:
#перевод в другой тип данных
    #met['mass']= met['mass'].astype('float32')

In [77]:
#уникальные значения
#met['year'].nunique()

In [78]:
#показать значения с индексами
# met.loc[[1003, 1002], 'year']
# met.iloc[[1003, 1002]]

In [ ]:
#for i in range(5):
#    print(met.iloc[[i], 1])

In [81]:
#met.nlargest(3, 'mass')

In [87]:
#met[met['mass']==21.0][['year']]

In [ ]:
#подсчет количества значений
#met['year'].value_counts()

In [98]:
met.groupby('fall')[['mass']].max()

             mass
fall
Fell   23000000.0
Found  60000000.0